### ISSUE TITLE
Audio card not recognised

### ISSUE THREAD

**Issue by JelleBakker** [dsperados/bear-examples#4]
Hi,

I am using an external usb audio card with a raspberry pi.
https://www.amazon.com/Channel-External-Sound-Audio-Adapter/dp/B007HISGRW/ref=sr_1_3?ie=UTF8&qid=1382967519&sr=8-3&keywords=usb+sound+card

The audio card is not recognised by bear(when I ask for all the audio outputs). But when I enter aplay -L in the command line of the raspberry pi, I do see the audio card.
So, it is recognised by the raspberry pi, but not by bear.

Jelle

**Comment by stijnfrishert** [comment]
Thanks, Jelle! I see you've issued this in the bear-audio repo as well, so I'll be closing this one. You'll be able to check further reference [here](https://github.com/dsperados/bear-audio/issues/15).
